const zone=document.getElementById('glitchZone');const win=document.querySelector('.fake-window');const button=document.getElementById('suspiciousButton');const title=document.getElementById('brokenTitle');const text=document.getElementById('brokenText');const bar=document.getElementById('progressBar');const potato=document.getElementById('potato');const follower=document.getElementById('follower');const panel=document.getElementById('repairPanel');const repairButton=document.getElementById('repairButton');const message=document.getElementById('message');const counter=document.getElementById('counter');const achievement=document.getElementById('achievement');const status=document.getElementById('status');
const glitches=[
 {name:'MOVING BUTTON',target:button,activate(){button.textContent='Click me???';button.style.transform='translateX(80px)'},repair(){button.textContent='Normal Button';button.style.transform=''}},
 {name:'BACKWARDS 404',target:title,activate(){title.textContent='404 — ton dnuoF egaP';title.classList.add('glitch')},repair(){title.textContent='404 — Page Not Found';title.classList.remove('glitch')}},
 {name:'BROKEN TEXT',target:text,activate(){text.textContent='The page that does exist does not exist. Wait...';text.classList.add('glitch')},repair(){text.textContent='The page you requested does not exist.';text.classList.remove('glitch')}},
 {name:'FAKE UPDATE',target:bar,activate(){bar.style.width='97%'},repair(){bar.style.width='7%'}},
 {name:'SECRET POTATO',target:potato,activate(){potato.textContent='🥔 GLITCH POTATO';potato.style.opacity='1'},repair(){potato.textContent='🥔';potato.style.opacity='.35'}},
 {name:'BROKEN NAVIGATION',target:win,activate(){win.style.transform='rotate(.7deg) skewX(1deg)';win.classList.add('glitch')},repair(){win.style.transform='';win.classList.remove('glitch')}},
 {name:'MYSTERIOUS Y',target:follower,activate(){follower.style.opacity='1';zone.addEventListener('mousemove',follow)},repair(){follower.style.opacity='0';zone.removeEventListener('mousemove',follow)}}
];
let found=new Set(),active=null,scanner=false;
function follow(e){const r=zone.getBoundingClientRect();follower.style.left=`${e.clientX-r.left+12}px`;follower.style.top=`${e.clientY-r.top+12}px`;follower.style.right='auto'}
function scan(){scanner=true;message.innerHTML='Scanner active. Look for something that does not belong here...';status.textContent='SYSTEM STATUS: SCANNING';status.classList.add('glitch');setTimeout(()=>{if(!active)detectNext()},450)}
function detectNext(){for(let i=0;i<glitches.length;i++){if(!found.has(i)){active=i;glitches[i].activate();panel.classList.add('visible');document.getElementById('repairText').textContent=`GLITCH DETECTED: ${glitches[i].name}`;message.innerHTML=`<strong>${glitches[i].name}</strong> detected. Press <strong>R</strong> to repair it.`;return}}finish()}
function repair(){if(active===null)return;glitches[active].repair();found.add(active);active=null;panel.classList.remove('visible');counter.textContent=`${found.size} / 7 FOUND`;status.textContent=`SYSTEM STATUS: ${found.size===7?'RESTORED':'UNSTABLE'}`;status.classList.remove('glitch');if(found.size===7){finish()}else{message.innerHTML='Glitch repaired! Press <strong>G</strong> to scan again.'}}
function finish(){scanner=false;panel.classList.remove('visible');achievement.classList.add('show');message.innerHTML='<strong>ALL 7 GLITCHES REPAIRED.</strong> You saved the 404 page. 🏆';status.textContent='SYSTEM STATUS: RESTORED';status.classList.remove('glitch');win.classList.remove('glitch')}
function reset(){location.reload()}
document.addEventListener('keydown',e=>{if(e.repeat)return;if(e.key.toLowerCase()==='g')scan();if(e.key.toLowerCase()==='r')repair();if(e.code==='Space'){e.preventDefault();reset()}});repairButton.addEventListener('click',repair);button.addEventListener('click',()=>{if(scanner&&active===0)repair()});
message.innerHTML='Press <strong>G</strong> to activate the scanner.';
